### ISSUE TITLE
"Failed to update Battle.net account" when signing in

### ISSUE THREAD

**Issue by antn** [cheshire137/competiwatch#107]
For some reason, when trying to sign in, I started getting an error last night that says "Failed to update Battle.net account <battletag>". 😱 

/cc @cheshire137

**Comment by cheshire137** [comment]
Thanks for the report @antn, I'll look into this!

**Comment by cheshire137** [comment]
You had two accounts. I merged them, your matches should all be preserved, let me know if something looks messed up. Please try logging in again!

**Comment by antn** [comment]
Looks like everything is working now! ✨ 

Thanks for your help!
