### ISSUE TITLE
Updating match rank does not update match result

### ISSUE THREAD

**Issue by RobThePM** [cheshire137/competiwatch#20]
i first entered a match as having gained SR.
then i went back and edited it so that i lost SR.
table shows W for a win, but negative SR.
picture below.

![image](https://user-images.githubusercontent.com/26153402/36411292-b39cb8ba-15c9-11e8-951f-ce5854d8ee4e.png)

**Comment by cheshire137** [comment]
I think this is a bug Jamie just described to me, too. He entered the same SR for two separate games accidentally, so the second one showed as a draw. When he edited the second one to fix the SR, it still showed as a draw.

Need to update the matches.result field after matches.rank changes.

**Comment by cheshire137** [comment]
This shouldn't happen again, thanks Rob! You will need to save your match to fix it, though. No need to change anything, just hitting save should do it.
