### ISSUE TITLE
Linking second account required me to click the connect button twice

### ISSUE THREAD

**Issue by antn** [cheshire137/competiwatch#21]
Hmm, I just tried adding my alt, and I noticed a possible bug! 

Steps:

1. Have an existing account
2. Click the connect button in your settings and go through the auth process
3. Be redirected back to competiwatch and see a flash message saying its linked
4. Observe that the other account isn't listed under "Your Accounts", even after refreshing
5. Click the connect button again and see that the account is now added under "Your Accounts"

**Comment by cheshire137** [comment]
Ooh interesting, I’ll try to reproduce this. Thanks!

**Comment by cheshire137** [comment]
I was able to reproduce this live, will try locally and see if I can fix what's going wrong.

**Comment by cheshire137** [comment]
I think this is fixed now. I just linked an account of mine and it only took the one click. Let me know if it happens again!
