### ISSUE TITLE
Finishing the last placement match prevents other matches from being entered

### ISSUE THREAD

**Issue by pseudobeard** [cheshire137/competiwatch#23]
Trying to view https://competiwatch.herokuapp.com/season/9/ATastySnack-1553 results in the "Something went wrong" error.

**Comment by cheshire137** [comment]
Thanks for the report! I’ll fix this one today.

**Comment by cheshire137** [comment]
Hmm I tried logging ten placement matches in season nine in my local development and nothing went wrong at the end. I may try making your season 9 publicly visible temporarily, see if me viewing it also results in an error.

**Comment by cheshire137** [comment]
Yep, that did it! I can work on a fix now. 😎

**Comment by cheshire137** [comment]
I just checked and your https://competiwatch.herokuapp.com/season/9/ATastySnack-1553 loads for me. I'll change the privacy on it so it's not publicly visible anymore.

However, I did notice something interesting. When I logged dummy placement matches locally, I did 10 of them and the last one had my placement rank:

<img width="319" alt="marchhare_11348___season_9___matches_-_competiwatch" src="https://user-images.githubusercontent.com/82317/36917228-e5a56e6a-1e1b-11e8-9856-902a5b6693e9.png">

In your season, I see P1-P9, and then a regular match with your rank:

<img width="272" alt="atastysnack_1553___season_9___matches_-_competiwatch" src="https://user-images.githubusercontent.com/82317/36917214-d3663180-1e1b-11e8-98b1-cec8c5df9d24.png">

I don't know how you logged only 9 placements and then made a regular non-placement match for your 10th. 🤔
