### ISSUE TITLE
Is 'near career high' graph showing correct career high?

### ISSUE THREAD

**Issue by RobThePM** [cheshire137/competiwatch#32]
Hi Chesh,

My season 8 career high is 3803, but the graph shows it at 3745.
3745 is my season end.
Is this working as intended?

![image](https://user-images.githubusercontent.com/26153402/36939027-325d38be-1edf-11e8-958f-683396c1377a.png)

![image](https://user-images.githubusercontent.com/26153402/36939029-3a8c83aa-1edf-11e8-9353-5cb3fdb3ea98.png)

Thanks,
Robert

**Comment by cheshire137** [comment]
Looking at your logged matches, it looks like the highest rank that's been logged is 3745, in season 8. Blizzard knows your for-real career high because it has data from every game you've ever played, but my app only knows what you've told it. So I think this is working as expected.

**Comment by RobThePM** [comment]
ahhhhh okay got it thanks.
sorry, end user error.
