### ISSUE TITLE
can we edit matches?

### ISSUE THREAD

**Issue by RobThePM** [cheshire137/competiwatch#37]
i just got this error when i tried to edit a match and hit save

![image](https://user-images.githubusercontent.com/26153402/36942412-93b10852-1f25-11e8-92fb-f87a713dfb51.png)

**Comment by cheshire137** [comment]
I bet you encountered what I just did when I was working on stuff locally. This is fixed in https://github.com/cheshire137/competiwatch/commit/37b84c71afd42f72d7c452e4cdbe852706868f12. Thanks for the report!
