### ISSUE TITLE
Content on page overlaps with header shadow

### ISSUE THREAD

**Issue by antn** [cheshire137/competiwatch#44]
It might be hard to see, but the content on the page overlaps on the shadow of the header:

<img width="462" alt="screen shot 2018-03-11 at 7 06 50 pm" src="https://user-images.githubusercontent.com/858504/37262284-70ac95a2-255f-11e8-9c9d-43f85894e86e.png">

**Comment by cheshire137** [comment]
OMG there's a header shadow? 😄 I didn't realize there was a shadow there! I'll fix this, thanks!
